In [31]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules


data = [
    {'Transaction': 1, 'Items': ['mleko', 'dżem', 'ser', 'chleb', 'masło']},
    {'Transaction': 2, 'Items': ['masło']},
    {'Transaction': 3, 'Items': ['jajka', 'ser', 'chleb', 'masło', 'dżem', 'mleko']},
    {'Transaction': 4, 'Items': ['jajka', 'mleko', 'ser']},
    {'Transaction': 5, 'Items': ['ser', 'jajka', 'masło', 'chleb', 'dżem', 'mleko']},
    {'Transaction': 6, 'Items': ['masło', 'ser']},
    {'Transaction': 7, 'Items': ['chleb', 'dżem', 'ser', 'masło', 'mleko', 'jajka']},
    {'Transaction': 8, 'Items': ['chleb', 'mleko', 'jajka', 'masło', 'ser']},
    {'Transaction': 9, 'Items': ['ser', 'chleb', 'dżem']},
    {'Transaction': 10, 'Items': ['dżem', 'ser', 'mleko', 'masło', 'chleb', 'jajka']},
    {'Transaction': 11, 'Items': ['ser', 'dżem', 'masło', 'mleko']},
    {'Transaction': 12, 'Items': ['chleb', 'mleko']},
    {'Transaction': 13, 'Items': ['jajka', 'masło', 'ser', 'mleko', 'chleb', 'dżem']},
    {'Transaction': 14, 'Items': ['ser', 'mleko', 'dżem', 'chleb']},
    {'Transaction': 15, 'Items': ['dżem', 'masło', 'ser', 'chleb', 'jajka']},
    {'Transaction': 16, 'Items': ['jajka', 'chleb', 'masło', 'ser']},
    {'Transaction': 17, 'Items': ['ser']},
    {'Transaction': 18, 'Items': ['ser', 'jajka']},
    {'Transaction': 19, 'Items': ['chleb', 'jajka', 'mleko']},
    {'Transaction': 20, 'Items': ['ser', 'jajka', 'mleko', 'chleb', 'masło', 'dżem']}
]


df = pd.DataFrame(data)
df

    Transaction                                    Items
0             1         [mleko, dżem, ser, chleb, masło]
1             2                                  [masło]
2             3  [jajka, ser, chleb, masło, dżem, mleko]
3             4                      [jajka, mleko, ser]
4             5  [ser, jajka, masło, chleb, dżem, mleko]
5             6                             [masło, ser]
6             7  [chleb, dżem, ser, masło, mleko, jajka]
7             8        [chleb, mleko, jajka, masło, ser]
8             9                       [ser, chleb, dżem]
9            10  [dżem, ser, mleko, masło, chleb, jajka]
10           11                [ser, dżem, masło, mleko]
11           12                           [chleb, mleko]
12           13  [jajka, masło, ser, mleko, chleb, dżem]
13           14                [ser, mleko, dżem, chleb]
14           15         [dżem, masło, ser, chleb, jajka]
15           16               [jajka, chleb, masło, ser]
16           17                                    [ser]
17           18                             [ser, jajka]
18           19                    [chleb, jajka, mleko]
19           20  [ser, jajka, mleko, chleb, masło, dżem]

In [37]:
kodowanie_bin = df['Items'].str.join('|').str.get_dummies().astype(bool)

czeste_powiazania = apriori(kodowanie_bin, min_support=0.5, use_colnames=True)

reguly = association_rules(czeste_powiazania, metric="confidence", min_threshold=0.7)

print(f"Frequent Itemsets: {czeste_powiazania}")

Frequent Itemsets:     support             itemsets
0      0.70              (chleb)
1      0.55               (dżem)
2      0.60              (jajka)
3      0.65              (masło)
4      0.65              (mleko)
5      0.85                (ser)
6      0.50        (chleb, dżem)
7      0.50       (jajka, chleb)
8      0.50       (masło, chleb)
9      0.55       (mleko, chleb)
10     0.60         (chleb, ser)
11     0.55          (dżem, ser)
12     0.55         (jajka, ser)
13     0.60         (masło, ser)
14     0.55         (mleko, ser)
15     0.50   (chleb, dżem, ser)
16     0.50  (masło, chleb, ser)

In [44]:
reguly[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

       antecedents   consequents  support  confidence      lift
0          (chleb)        (dżem)     0.50    0.714286  1.298701
1           (dżem)       (chleb)     0.50    0.909091  1.298701
2          (jajka)       (chleb)     0.50    0.833333  1.190476
3          (chleb)       (jajka)     0.50    0.714286  1.190476
4          (masło)       (chleb)     0.50    0.769231  1.098901
5          (chleb)       (masło)     0.50    0.714286  1.098901
6          (mleko)       (chleb)     0.55    0.846154  1.208791
7          (chleb)       (mleko)     0.55    0.785714  1.208791
8          (chleb)         (ser)     0.60    0.857143  1.008403
9            (ser)       (chleb)     0.60    0.705882  1.008403
10          (dżem)         (ser)     0.55    1.000000  1.176471
11         (jajka)         (ser)     0.55    0.916667  1.078431
12         (masło)         (ser)     0.60    0.923077  1.085973
13           (ser)       (masło)     0.60    0.705882  1.085973
14         (mleko)         (ser)     0.55    0.846154  0.995475
15   (chleb, dżem)         (ser)     0.50    1.000000  1.176471
16    (chleb, ser)        (dżem)     0.50    0.833333  1.515152
17     (dżem, ser)       (chleb)     0.50    0.909091  1.298701
18         (chleb)   (dżem, ser)     0.50    0.714286  1.298701
19          (dżem)  (chleb, ser)     0.50    0.909091  1.515152
20  (masło, chleb)         (ser)     0.50    1.000000  1.176471
21    (masło, ser)       (chleb)     0.50    0.833333  1.190476
22    (chleb, ser)       (masło)     0.50    0.833333  1.282051
23         (masło)  (chleb, ser)     0.50    0.769231  1.282051
24         (chleb)  (masło, ser)     0.50    0.714286  1.190476